# Generated by Django 6.0.4 on 2026-04-23 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMoodLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "avg_sentiment",
                    models.FloatField(verbose_name="Средняя тональность"),
                ),
                (
                    "dominant_emotion",
                    models.CharField(
                        max_length=100, verbose_name="Доминирующая эмоция"
                    ),
                ),
                (
                    "emotional_tags",
                    models.JSONField(default=list, verbose_name="Эмоциональные теги"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
    ]
