# Generated by Django 6.0.4 on 2026-04-23 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название службы"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "country_code",
                    models.CharField(
                        max_length=10, verbose_name="Код страны (напр. TM, RU, DE)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "summary",
                    models.TextField(
                        blank=True, verbose_name="Краткое содержание сессии"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия чата",
                "verbose_name_plural": "Сессии чата",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "Пользователь"), ("ai", "ИИ-компаньон")],
                        max_length=4,
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст сообщения")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "is_trigger_alert",
                    models.BooleanField(
                        default=False, verbose_name="Критический маркер"
                    ),
                ),
                (
                    "sentiment_value",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Тональность (-1 до 1)"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatsession",
                    ),
                ),
            ],
        ),
    ]
