# Generated by Django 6.0.4 on 2026-04-26 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmergencyResource',
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='summary',
        ),
        migrations.AddField(
            model_name='message',
            name='anger',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='message',
            name='anxiety',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='message',
            name='apathy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='message',
            name='primary_emotion',
            field=models.CharField(default='neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='sadness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='message',
            name='stress_factors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_trigger_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='sentiment_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
    ]
